# -*- coding: utf-8 -*-
"""Text Summarization with PEGASUS and T5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKYgrwW1BbCxeOcU-7lO2w31ebT7-_yO
"""

# text_summarization.py

from transformers import PegasusForConditionalGeneration, PegasusTokenizer, T5ForConditionalGeneration, T5Tokenizer

def summarize_with_pegasus(text):
    print("\n🔹 PEGASUS Summary:")
    model_name = "google/pegasus-xsum"
    tokenizer = PegasusTokenizer.from_pretrained(model_name)
    model = PegasusForConditionalGeneration.from_pretrained(model_name)

    tokens = tokenizer(text, truncation=True, padding="longest", return_tensors="pt")
    summary_ids = model.generate(**tokens)
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    print(summary)

def summarize_with_t5(text):
    print("\n🔹 T5 Summary:")
    model_name = "t5-base"
    tokenizer = T5Tokenizer.from_pretrained(model_name)
    model = T5ForConditionalGeneration.from_pretrained(model_name)

    input_text = "summarize: " + text
    tokens = tokenizer(input_text, truncation=True, padding="longest", return_tensors="pt")
    summary_ids = model.generate(**tokens)
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    print(summary)

def main():
    text = (
        "The Apollo 11 mission was the first manned mission to land on the Moon. "
        "Launched by NASA on July 16, 1969, the mission carried three astronauts: "
        "Neil Armstrong, Buzz Aldrin, and Michael Collins. On July 20, 1969, Neil Armstrong "
        "became the first person to step onto the lunar surface, followed shortly by Aldrin. "
        "The mission marked a significant achievement in space exploration and was a key moment in human history."
    )

    summarize_with_pegasus(text)
    summarize_with_t5(text)

if __name__ == "__main__":
    main()